### ISSUE TITLE
requestsをrequirements.txtに追加が必要

### ISSUE THREAD

**Issue by ktamamu** [ktamamu/NeKo_AWS_SG#3]
初回実行時に以下のエラーが出力された。
```zsh
python src/main.py
Traceback (most recent call last):
  File "./NeKo_AWS_SG/src/main.py", line 7, in <module>
    from utils import (
  File "./NeKo_AWS_SG/src/utils.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
下記で解消したので、requests.txtにもあらかじめ記載しておく。
```zsh
pip install requests
```

**Comment by ktamamu** [comment]
修正済み　[c8f3408](https://github.com/ktamamu/NeKo_AWS_SG/commit/c8f340833071fcff4750a3db51fa1e336c6a6391)
